# Generated by Django 6.0.8 on 2026-08-04 20:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='شماره سفارش')),
                ('session_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه نشست')),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ کل سفارش (تومان)')),
                ('status', models.CharField(choices=[('pending_payment', 'در انتظار پرداخت'), ('paid', 'پرداخت موفق و صادر شده'), ('cancelled', 'لغو شده'), ('failed', 'ناموفق')], default='pending_payment', max_length=30, verbose_name='وضعیت سفارش')),
                ('collected_info', models.JSONField(default=dict, verbose_name='اطلاعات تکمیل شده بیمه\u200cنامه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت سفارش')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'سفارش بیمه',
                'verbose_name_plural': 'سفارشات بیمه',
                'ordering': ['-created_at'],
            },
        ),
    ]
