# Generated by Django 6.0.8 on 2026-08-04 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='recommendation.insuranceplan', verbose_name='طرح بیمه خریداری شده'),
        ),
    ]
