# Generated by Django 6.0.8 on 2026-08-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='selected_coverages',
            field=models.JSONField(blank=True, default=list, verbose_name='پوشش\u200cهای انتخابی'),
        ),
    ]
