# Generated by Django 6.0.8 on 2026-09-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_selected_coverages'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='down_payment_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مبلغ پیش\u200cپرداخت (تومان)'),
        ),
        migrations.AddField(
            model_name='order',
            name='installment_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مبلغ هر قسط (تومان)'),
        ),
        migrations.AddField(
            model_name='order',
            name='installment_count',
            field=models.IntegerField(default=0, verbose_name='تعداد اقساط'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'نقدی'), ('installment_3', 'اقساطی ۳ ماهه'), ('installment_6', 'اقساطی ۶ ماهه')], default='cash', max_length=30, verbose_name='روش پرداخت'),
        ),
    ]
