# Generated by Django 6.0.8 on 2026-09-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_down_payment_amount_order_installment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_installments_count',
            field=models.IntegerField(default=1, verbose_name='تعداد اقساط پرداخت\u200cشده'),
        ),
    ]
