# Generated by Django 6.0.8 on 2026-08-04 20:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'کاربر'), ('assistant', 'دستیار هوشمند'), ('system', 'سیستم')], max_length=20, verbose_name='نقش ارسال\u200cکننده')),
                ('content', models.TextField(verbose_name='متن پیام')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='متاداده تکمیلی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
            ],
            options={
                'verbose_name': 'پیام گفتگو',
                'verbose_name_plural': 'پیام\u200cهای گفتگو',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='گفتگو با دستیار هوشمند بیمه', max_length=255, verbose_name='عنوان گفتگو')),
                ('insurance_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع بیمه مورد نیاز')),
                ('collected_data', models.JSONField(default=dict, verbose_name='اطلاعات جمع\u200cآوری شده')),
                ('is_completed', models.BooleanField(default=False, verbose_name='تکمیل گفتگو و صدور سفارش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'نشست گفتگو',
                'verbose_name_plural': 'نشست\u200cهای گفتگو',
                'ordering': ['-updated_at'],
            },
        ),
    ]
