# Generated by Django 6.0.8 on 2026-08-04 20:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='شناسه تراکنش درگاه')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ پرداختی (تومان)')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پردازش'), ('success', 'پرداخت موفق'), ('failed', 'پرداخت ناموفق')], default='pending', max_length=20, verbose_name='وضعیت پرداخت')),
                ('payment_gateway', models.CharField(default='sandbox', max_length=50, verbose_name='درگاه پرداخت')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان دقیق پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد تراکنش')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='سفارش مرتبط')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'تراکنش\u200cهای پرداخت',
                'ordering': ['-created_at'],
            },
        ),
    ]
