# Generated by Django 6.0.8 on 2026-08-04 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام شرکت بیمه')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد شناسه')),
                ('logo_url', models.URLField(blank=True, null=True, verbose_name='آدرس لوگو')),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=3, verbose_name='امتیاز مشتریان (۱ تا ۵)')),
                ('wealth_level', models.IntegerField(default=1, verbose_name='سطح توانگری مالی')),
                ('complaint_satisfaction_rate', models.IntegerField(default=95, verbose_name='درصد رضایت\u200cمندی از پرداخت خسارت')),
            ],
            options={
                'verbose_name': 'شرکت بیمه',
                'verbose_name_plural': 'شرکت\u200cهای بیمه',
            },
        ),
        migrations.CreateModel(
            name='InsurancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان طرح بیمه')),
                ('insurance_type', models.CharField(choices=[('third_party', 'شخص ثالث خودرو'), ('body', 'بدنه خودرو'), ('health', 'درمان تکمیلی'), ('travel', 'مسافرتی خارج از کشور'), ('life', 'عمر و سرمایه\u200cگذاری')], max_length=50, verbose_name='نوع بیمه')),
                ('description', models.TextField(verbose_name='توضیحات و پوشش\u200cها')),
                ('base_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت پایه (تومان)')),
                ('coverage_amount', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='حداکثر سقف تعهد مالی (تومان)')),
                ('coverage_details', models.JSONField(default=list, verbose_name='جزئیات پوشش\u200cها به تفکیک')),
                ('max_discount_percent', models.IntegerField(default=70, verbose_name='حداکثر درصد تخفیف عدم خسارت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='recommendation.insurancecompany', verbose_name='شرکت بیمه\u200cگر')),
            ],
            options={
                'verbose_name': 'طرح بیمه',
                'verbose_name_plural': 'طرح\u200cهای بیمه',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, verbose_name='شناسه نشست گفتگو')),
                ('calculated_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت محاسبه شده (تومان)')),
                ('original_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت قبل از تخفیف (تومان)')),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مبلغ تخفیف (تومان)')),
                ('recommendation_reason', models.TextField(verbose_name='دلیل پیشنهاد هوشمند')),
                ('collected_data', models.JSONField(default=dict, verbose_name='اطلاعات ورودی کاربر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ پیشنهاد')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.insuranceplan', verbose_name='طرح بیمه پیشنهادی')),
            ],
            options={
                'verbose_name': 'پیشنهاد هوشمند',
                'verbose_name_plural': 'پیشنهادات هوشمند',
            },
        ),
    ]
