# Generated by Django 6.0.8 on 2026-08-26 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام پوشش')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات پوشش')),
                ('coverage_type', models.CharField(choices=[('BASE', 'پوشش اصلی / پایه'), ('OPTIONAL', 'پوشش اختیاری / تکمیلی')], default='OPTIONAL', max_length=20, verbose_name='نوع پوشش')),
                ('additional_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مبلغ اضافه (تومان)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to='recommendation.insuranceplan', verbose_name='طرح بیمه مرتبط')),
            ],
            options={
                'verbose_name': 'پوشش بیمه',
                'verbose_name_plural': 'پوشش\u200cهای بیمه',
                'ordering': ['coverage_type', 'name'],
            },
        ),
    ]
