# Generated by Django 6.0.8 on 2026-09-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_insurancecoverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceplan',
            name='allow_3_months',
            field=models.BooleanField(default=True, verbose_name='امکان اقساط ۳ ماهه'),
        ),
        migrations.AddField(
            model_name='insuranceplan',
            name='allow_6_months',
            field=models.BooleanField(default=True, verbose_name='امکان اقساط ۶ ماهه'),
        ),
        migrations.AddField(
            model_name='insuranceplan',
            name='down_payment_percent',
            field=models.IntegerField(default=20, verbose_name='درصد پیش\u200cپرداخت'),
        ),
        migrations.AddField(
            model_name='insuranceplan',
            name='is_installment_enabled',
            field=models.BooleanField(default=True, verbose_name='امکان پرداخت اقساطی'),
        ),
        migrations.AlterField(
            model_name='insuranceplan',
            name='insurance_type',
            field=models.CharField(choices=[('third_party', 'شخص ثالث خودرو'), ('body', 'بدنه خودرو'), ('fire', 'آتش\u200cسوزی و زلزله'), ('travel', 'مسافرتی خارج از کشور'), ('life', 'عمر و سرمایه\u200cگذاری'), ('health', 'درمان تکمیلی')], max_length=50, verbose_name='نوع بیمه'),
        ),
    ]
