# Generated by Django 6.0.8 on 2026-08-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'کاربر عادی'), ('ADMIN', 'مدیر سیستم')], default='USER', max_length=10, verbose_name='نقش کاربری'),
        ),
    ]
