# Generated by Django 6.0.8 on 2026-09-22 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0004_insuranceplan_allow_3_months_and_more'),
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experts', to='recommendation.insurancecompany', verbose_name='شرکت بیمه تخصیص\u200cیافته'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_approved_expert',
            field=models.BooleanField(default=False, verbose_name='تایید صلاحیت کارشناس توسط مدیریت'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'کاربر عادی'), ('ADMIN', 'مدیر سیستم'), ('EXPERT', 'کارشناس بیمه')], default='USER', max_length=10, verbose_name='نقش کاربری'),
        ),
    ]
